"""add centerline points and node sequence

Revision ID: 0b008190ff6c
Revises: 79f92a8010e4
Create Date: 2026-04-14 03:30:52.128238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b008190ff6c'
down_revision: Union[str, Sequence[str], None] = '79f92a8010e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('is_approved', sa.Boolean(), nullable=True))
    op.add_column('holes', sa.Column('is_approved', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.drop_column('holes', 'is_approved')
    op.drop_column('courses', 'is_approved')
    # ### end Alembic commands ###
