"""drop hole_centerline_points

Revision ID: 2ff0fc5dd10a
Revises: acb99646c70f
Create Date: 2026-04-29 19:42:03.099220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ff0fc5dd10a'
down_revision: Union[str, Sequence[str], None] = 'acb99646c70f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hole_centerline_points')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hole_centerline_points',
    sa.Column('point_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('hole_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sequence', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['hole_id'], ['holes.hole_id'], name=op.f('hole_centerline_points_hole_id_fkey')),
    sa.PrimaryKeyConstraint('point_id', name=op.f('hole_centerline_points_pkey'))
    )
    # ### end Alembic commands ###
