"""add centerline points and node sequence

Revision ID: 365ebf52c179
Revises: 0b008190ff6c
Create Date: 2026-04-14 04:15:18.408708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '365ebf52c179'
down_revision: Union[str, Sequence[str], None] = '0b008190ff6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('city', sa.String(), nullable=True))
    op.add_column('courses', sa.Column('state', sa.String(), nullable=True))
    op.add_column('courses', sa.Column('address', sa.String(), nullable=True))
    op.drop_column('courses', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('courses', 'address')
    op.drop_column('courses', 'state')
    op.drop_column('courses', 'city')
    # ### end Alembic commands ###
