"""initial schema

Revision ID: 40a979aeaefe
Revises: 
Create Date: 2026-04-09 14:49:06.983622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40a979aeaefe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('total_par', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('course_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('google_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('google_id')
    )
    op.create_table('bags',
    sa.Column('bag_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('bag_id')
    )
    op.create_table('discs',
    sa.Column('disc_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('disc_type', sa.Enum('putter', 'midrange', 'fairway_driver', 'distance_driver', name='disc_type_enum'), nullable=False),
    sa.Column('manufacturer', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('glide', sa.Float(), nullable=True),
    sa.Column('turn', sa.Float(), nullable=True),
    sa.Column('fade', sa.Float(), nullable=True),
    sa.Column('wear', sa.Float(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('disc_id')
    )
    op.create_table('holes',
    sa.Column('hole_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('hole_number', sa.Integer(), nullable=False),
    sa.Column('par', sa.Integer(), nullable=False),
    sa.Column('distance', sa.Integer(), nullable=True),
    sa.Column('elevation', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ),
    sa.PrimaryKeyConstraint('hole_id')
    )
    op.create_table('user_stats',
    sa.Column('stat_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('c1_percent', sa.Float(), nullable=True),
    sa.Column('c1x_percent', sa.Float(), nullable=True),
    sa.Column('c2_percent', sa.Float(), nullable=True),
    sa.Column('gir_c1', sa.Float(), nullable=True),
    sa.Column('gir_c2', sa.Float(), nullable=True),
    sa.Column('parked', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('stat_id')
    )
    op.create_table('user_throw_style',
    sa.Column('throw_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hand', sa.Enum('right', 'left', name='hand_enum'), nullable=False),
    sa.Column('throw_type', sa.Enum('backhand', 'forehand', name='throw_type_enum'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('throw_id')
    )
    op.create_table('bag_disc',
    sa.Column('bag_id', sa.Integer(), nullable=False),
    sa.Column('disc_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bag_id'], ['bags.bag_id'], ),
    sa.ForeignKeyConstraint(['disc_id'], ['discs.disc_id'], ),
    sa.PrimaryKeyConstraint('bag_id', 'disc_id')
    )
    op.create_table('hole_hazards',
    sa.Column('hazard_id', sa.Integer(), nullable=False),
    sa.Column('hole_id', sa.Integer(), nullable=False),
    sa.Column('hazard_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['hole_id'], ['holes.hole_id'], ),
    sa.PrimaryKeyConstraint('hazard_id')
    )
    op.create_table('hole_nodes',
    sa.Column('hole_node_id', sa.Integer(), nullable=False),
    sa.Column('hole_id', sa.Integer(), nullable=False),
    sa.Column('node_type', sa.Enum('tee', 'landing_zone', 'mando', 'dogleg', 'basket', name='node_type_enum'), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['hole_id'], ['holes.hole_id'], ),
    sa.PrimaryKeyConstraint('hole_node_id')
    )
    op.create_table('rounds',
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('bag_id', sa.Integer(), nullable=False),
    sa.Column('played_at', sa.DateTime(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bag_id'], ['bags.bag_id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('round_id')
    )
    op.create_table('user_disc_stats',
    sa.Column('stat_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('disc_id', sa.Integer(), nullable=False),
    sa.Column('avg_distance', sa.Integer(), nullable=True),
    sa.Column('max_distance', sa.Integer(), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.Column('measured_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['disc_id'], ['discs.disc_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('stat_id')
    )
    op.create_table('hole_edges',
    sa.Column('hole_edge_id', sa.Integer(), nullable=False),
    sa.Column('from_node_id', sa.Integer(), nullable=False),
    sa.Column('to_node_id', sa.Integer(), nullable=False),
    sa.Column('distance', sa.Integer(), nullable=False),
    sa.Column('required_line_shape', sa.Enum('hyzer', 'anhyzer', 'flat', 'spike_hyzer', 'roller', name='line_shape_enum'), nullable=False),
    sa.ForeignKeyConstraint(['from_node_id'], ['hole_nodes.hole_node_id'], ),
    sa.ForeignKeyConstraint(['to_node_id'], ['hole_nodes.hole_node_id'], ),
    sa.PrimaryKeyConstraint('hole_edge_id')
    )
    op.create_table('round_holes',
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('hole_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hole_id'], ['holes.hole_id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.round_id'], ),
    sa.PrimaryKeyConstraint('round_id', 'hole_id')
    )
    op.create_table('round_stats',
    sa.Column('stat_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('c1_percent', sa.Float(), nullable=True),
    sa.Column('c1x_percent', sa.Float(), nullable=True),
    sa.Column('c2_percent', sa.Float(), nullable=True),
    sa.Column('gir_c1', sa.Float(), nullable=True),
    sa.Column('gir_c2', sa.Float(), nullable=True),
    sa.Column('parked', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.round_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('stat_id')
    )
    op.create_table('edge_hazards',
    sa.Column('hazard_id', sa.Integer(), nullable=False),
    sa.Column('hole_edge_id', sa.Integer(), nullable=False),
    sa.Column('hazard_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['hole_edge_id'], ['hole_edges.hole_edge_id'], ),
    sa.PrimaryKeyConstraint('hazard_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('edge_hazards')
    op.drop_table('round_stats')
    op.drop_table('round_holes')
    op.drop_table('hole_edges')
    op.drop_table('user_disc_stats')
    op.drop_table('rounds')
    op.drop_table('hole_nodes')
    op.drop_table('hole_hazards')
    op.drop_table('bag_disc')
    op.drop_table('user_throw_style')
    op.drop_table('user_stats')
    op.drop_table('holes')
    op.drop_table('discs')
    op.drop_table('bags')
    op.drop_table('users')
    op.drop_table('courses')
    # ### end Alembic commands ###
