"""add centerline points and node sequence

Revision ID: 79f92a8010e4
Revises: d06d7b1b74f2
Create Date: 2026-04-14 03:26:32.049430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '79f92a8010e4'
down_revision: Union[str, Sequence[str], None] = 'd06d7b1b74f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hole_centerline_points',
    sa.Column('point_id', sa.Integer(), nullable=False),
    sa.Column('hole_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['hole_id'], ['holes.hole_id'], ),
    sa.PrimaryKeyConstraint('point_id')
    )
    op.alter_column('hole_edges', 'required_line_shape',
               existing_type=postgresql.ENUM('hyzer', 'anhyzer', 'flat', 'spike_hyzer', 'roller', name='line_shape_enum'),
               nullable=True)
    op.add_column('hole_nodes', sa.Column('sequence', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hole_nodes', 'sequence')
    op.alter_column('hole_edges', 'required_line_shape',
               existing_type=postgresql.ENUM('hyzer', 'anhyzer', 'flat', 'spike_hyzer', 'roller', name='line_shape_enum'),
               nullable=False)
    op.drop_table('hole_centerline_points')
    # ### end Alembic commands ###
