"""add fairway_width to hole_edge

Revision ID: 8c073174be2c
Revises: c34138960194
Create Date: 2026-04-14 22:15:58.618501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c073174be2c'
down_revision: Union[str, Sequence[str], None] = 'c34138960194'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hole_edges', sa.Column('fairway_width', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hole_edges', 'fairway_width')
    # ### end Alembic commands ###
