"""initial schema

Revision ID: ab4e26fd665a
Revises: 
Create Date: 2026-04-09 03:27:00.767148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab4e26fd665a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('total_par', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('course_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('google_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('c1_percent', sa.Float(), nullable=True),
    sa.Column('c1x_percent', sa.Float(), nullable=True),
    sa.Column('c2_percent', sa.Float(), nullable=True),
    sa.Column('gir_c1', sa.Float(), nullable=True),
    sa.Column('gir_c2', sa.Float(), nullable=True),
    sa.Column('parked', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('google_id')
    )
    op.create_table('bags',
    sa.Column('bag_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('bag_id')
    )
    op.create_table('discs',
    sa.Column('disc_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('glide', sa.Float(), nullable=True),
    sa.Column('turn', sa.Float(), nullable=True),
    sa.Column('fade', sa.Float(), nullable=True),
    sa.Column('wear', sa.Float(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('disc_type', sa.String(), nullable=True),
    sa.Column('manufacturer', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('throw_distance', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('disc_id')
    )
    op.create_table('holes',
    sa.Column('hole_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('hole_number', sa.Integer(), nullable=True),
    sa.Column('par', sa.Integer(), nullable=True),
    sa.Column('distance', sa.Integer(), nullable=True),
    sa.Column('elevation', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ),
    sa.PrimaryKeyConstraint('hole_id')
    )
    op.create_table('bag_disc',
    sa.Column('bag_id', sa.Integer(), nullable=False),
    sa.Column('disc_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bag_id'], ['bags.bag_id'], ),
    sa.ForeignKeyConstraint(['disc_id'], ['discs.disc_id'], ),
    sa.PrimaryKeyConstraint('bag_id', 'disc_id')
    )
    op.create_table('hole_nodes',
    sa.Column('hole_node_id', sa.Integer(), nullable=False),
    sa.Column('hole_id', sa.Integer(), nullable=False),
    sa.Column('node_type', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['hole_id'], ['holes.hole_id'], ),
    sa.PrimaryKeyConstraint('hole_node_id')
    )
    op.create_table('hole_edges',
    sa.Column('hole_edge_id', sa.Integer(), nullable=False),
    sa.Column('from_node_id', sa.Integer(), nullable=False),
    sa.Column('to_node_id', sa.Integer(), nullable=False),
    sa.Column('distance', sa.Integer(), nullable=True),
    sa.Column('required_line_shape', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['from_node_id'], ['hole_nodes.hole_node_id'], ),
    sa.ForeignKeyConstraint(['to_node_id'], ['hole_nodes.hole_node_id'], ),
    sa.PrimaryKeyConstraint('hole_edge_id')
    )
    op.create_table('hazards',
    sa.Column('hazard_id', sa.Integer(), nullable=False),
    sa.Column('hole_id', sa.Integer(), nullable=False),
    sa.Column('hole_edge_id', sa.Integer(), nullable=True),
    sa.Column('hazard_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['hole_edge_id'], ['hole_edges.hole_edge_id'], ),
    sa.ForeignKeyConstraint(['hole_id'], ['holes.hole_id'], ),
    sa.PrimaryKeyConstraint('hazard_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hazards')
    op.drop_table('hole_edges')
    op.drop_table('hole_nodes')
    op.drop_table('bag_disc')
    op.drop_table('holes')
    op.drop_table('discs')
    op.drop_table('bags')
    op.drop_table('users')
    op.drop_table('courses')
    # ### end Alembic commands ###
