"""add centerline distance to hole nodes

Revision ID: c34138960194
Revises: 365ebf52c179
Create Date: 2026-04-14 14:14:16.903417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c34138960194'
down_revision: Union[str, Sequence[str], None] = '365ebf52c179'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hole_edges', 'required_line_shape')
    op.add_column('hole_nodes', sa.Column('centerline_distance', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hole_nodes', 'centerline_distance')
    op.add_column('hole_edges', sa.Column('required_line_shape', postgresql.ENUM('hyzer', 'anhyzer', 'flat', 'spike_hyzer', 'roller', name='line_shape_enum'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
