"""add coordinates to hole nodes

Revision ID: d06d7b1b74f2
Revises: 40a979aeaefe
Create Date: 2026-04-10 13:58:43.745876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd06d7b1b74f2'
down_revision: Union[str, Sequence[str], None] = '40a979aeaefe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hole_nodes', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('hole_nodes', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hole_nodes', 'longitude')
    op.drop_column('hole_nodes', 'latitude')
    # ### end Alembic commands ###
